=== DamilolaAdegunwa/docson/docs/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://www.tomware.ch/integrationmessage.schema.json",
  "title": "Describes an integration message definition",
  "description": "some description",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "title": "Name of the message definition.",
      "description": "Meaningful name for the message definition."
    },
    "version": {
      "type": "number",
      "title": "Version of the message.",
      "description": "Provide a version number for the message."
    },
    "producer": {
      "type": "string",
      "title": "Producer of the message.",
      "description": "Provide the name of the producer service that will publish this message."
    },
    "message": {
      "type": "object",
      "title": "The message definition.",
      "description": "Provide the message that needs to be documented.",
      "properties": {
        "properties": {
          "type": "object",
          "title": "Properties of the message definition.",
          "description": "Properties of and instance of the message definition.",
          "properties": {
            "id": {
              "type": "object",
              "description": "A unique id of a message instance."
            },
            "timeStamp": {
              "type": "object",
              "description": "The timestamp of a message instance."
            }
          },
          "required": [
            "id",
            "timeStamp"
          ]
        }
      },
      "required": [
        "properties"
      ]
    },
    "sample": {
      "type": "object",
      "title": "A sample for a message definition.",
      "description": "Provides a sample instance of a message that needs to be documented."
    },
    "tags": {
      "type": "array",
      "title": "Tags for that apply to the message",
      "description": "Provide tags that are related to the message (i.e. domain)",
      "items": {
        "type": "string"
      }
    }
  },
  "required": [
    "name",
    "version",
    "producer",
    "message"
  ]
}

=== DamilolaAdegunwa/docson/src/wwwroot/data/types/deviceServiceReadyMessageDefinition.json
{
  "$schema": "./schema.json",
  "name": "DeviceServiceReadyMessage",
  "version": 1.0,
  "producer": "DeviceService",
  "message": {
    "properties": {
      "id": {
        "type": "string",
        "description": "A unique id for the message."
      },
      "timeStamp": {
        "type": "date",
        "description": "Creation date for the message."
      }
    }
  },
  "sample": {
    "id": "SomeId-Guid-WhatElse",
    "timeStamp": "2012-04-21T18:25:43-05:00"
  },
  "tags": [
    "DeviceService"
  ]
}

=== DamilolaAdegunwa/docson/src/wwwroot/types/sampleMessageDefinition.json
{
  "$schema": "./schema.json",
  "name": "SampleMessage",
  "version": 1.0,
  "producer": "DeviceService",
  "message": {
    "properties": {
      "id": {
        "type": "string"
      },
      "timeStamp": {
        "type": "date"
      },
      "deviceIdent": {
        "type": "string"
      },
      "configuration": {
        "type": "string"
      }
    }
  },
  "tags": [
    "DeviceService",
    "SomeOther",
    "Another"
  ]
}

=== DamilolaAdegunwa/docson/src/wwwroot/data/types/deviceServiceReadyMessageDefinition.v2.json
{
  "$schema": "./schema.json",
  "name": "DeviceServiceReadyMessage",
  "version": 2.0,
  "producer": "DeviceService",
  "message": {
    "properties": {
      "id": {
        "type": "string",
        "description": "A unique id for the message."
      },
      "timeStamp": {
        "type": "date",
        "description": "Creation date for the message."
      },
      "ident": {
        "type": "string",
        "description": "Ident of the device service."
      }
    }
  },
  "sample": {
    "id": "SomeId-Guid-WhatElse",
    "timeStamp": "2012-04-21T18:25:43-05:00",
    "ident": "BarCodeScannerDeviceService"
  },
  "tags": [
    "DeviceService"
  ]
}
